revert edc version to 3.1 reason: not working postgres-flyway extension

diff --git a/src/launcher/build/scripts/launcher b/src/launcher/build/scripts/launcher
--- a/src/launcher/build/scripts/launcher
+++ b/src/launcher/build/scripts/launcher
@@ -83,10 +83,8 @@ done
 # This is normally unused
 # shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
-
-# Add default JVM options here. You can also use JAVA_OPTS and LAUNCHER_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS=""
+# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
+APP_HOME=$( cd "${APP_HOME:-./}.." > /dev/null && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -114,7 +112,7 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/launcher.jar:$APP_HOME/lib/postgres-flyway.jar:$APP_HOME/lib/data-dashboard-local.jar:$APP_HOME/lib/control-plane-core-0.4.1.jar:$APP_HOME/lib/control-plane-api-client-0.4.1.jar:$APP_HOME/lib/dsp-0.4.1.jar:$APP_HOME/lib/configuration-filesystem-0.4.1.jar:$APP_HOME/lib/vault-filesystem-0.4.1.jar:$APP_HOME/lib/management-api-0.4.1.jar:$APP_HOME/lib/transfer-data-plane-0.4.1.jar:$APP_HOME/lib/transfer-pull-http-receiver-0.4.1.jar:$APP_HOME/lib/data-plane-selector-api-0.4.1.jar:$APP_HOME/lib/data-plane-selector-core-0.4.1.jar:$APP_HOME/lib/data-plane-selector-client-0.4.1.jar:$APP_HOME/lib/data-plane-api-0.4.1.jar:$APP_HOME/lib/data-plane-core-0.4.1.jar:$APP_HOME/lib/data-plane-http-0.4.1.jar:$APP_HOME/lib/api-observability-0.4.1.jar:$APP_HOME/lib/iam-mock-0.4.1.jar:$APP_HOME/lib/auth-tokenbased-0.4.1.jar:$APP_HOME/lib/control-plane-sql-0.4.1.jar:$APP_HOME/lib/data-plane-instance-store-sql-0.4.1.jar:$APP_HOME/lib/sql-pool-apache-commons-0.4.1.jar:$APP_HOME/lib/contract-negotiation-store-sql-0.4.1.jar:$APP_HOME/lib/transfer-process-store-sql-0.4.1.jar:$APP_HOME/lib/sql-lease-0.4.1.jar:$APP_HOME/lib/asset-index-sql-0.4.1.jar:$APP_HOME/lib/contract-definition-store-sql-0.4.1.jar:$APP_HOME/lib/policy-definition-store-sql-0.4.1.jar:$APP_HOME/lib/sql-core-0.4.1.jar:$APP_HOME/lib/transaction-local-0.4.1.jar:$APP_HOME/lib/boot-0.4.1.jar:$APP_HOME/lib/federated-catalog-core-0.4.1.jar:$APP_HOME/lib/federated-catalog-api-0.4.1.jar:$APP_HOME/lib/contract-core-0.4.1.jar:$APP_HOME/lib/transfer-core-0.4.1.jar:$APP_HOME/lib/connector-core-0.4.1.jar:$APP_HOME/lib/control-plane-aggregate-services-0.4.1.jar:$APP_HOME/lib/asset-api-0.4.1.jar:$APP_HOME/lib/catalog-api-0.4.1.jar:$APP_HOME/lib/contract-agreement-api-0.4.1.jar:$APP_HOME/lib/contract-definition-api-0.4.1.jar:$APP_HOME/lib/contract-negotiation-api-0.4.1.jar:$APP_HOME/lib/policy-definition-api-0.4.1.jar:$APP_HOME/lib/transfer-process-api-0.4.1.jar:$APP_HOME/lib/management-api-configuration-0.4.1.jar:$APP_HOME/lib/control-api-configuration-0.4.1.jar:$APP_HOME/lib/api-core-0.4.1.jar:$APP_HOME/lib/data-plane-client-0.4.1.jar:$APP_HOME/lib/catalog-core-0.4.1.jar:$APP_HOME/lib/data-plane-selector-spi-0.4.1.jar:$APP_HOME/lib/data-plane-util-0.4.1.jar:$APP_HOME/lib/util-0.4.1.jar:$APP_HOME/lib/dsp-catalog-0.4.1.jar:$APP_HOME/lib/dsp-catalog-api-0.4.1.jar:$APP_HOME/lib/dsp-negotiation-0.4.1.jar:$APP_HOME/lib/dsp-negotiation-api-0.4.1.jar:$APP_HOME/lib/dsp-transfer-process-0.4.1.jar:$APP_HOME/lib/dsp-transfer-process-api-0.4.1.jar:$APP_HOME/lib/dsp-transfer-process-http-dispatcher-0.4.1.jar:$APP_HOME/lib/control-plane-spi-0.4.1.jar:$APP_HOME/lib/dsp-catalog-http-dispatcher-0.4.1.jar:$APP_HOME/lib/dsp-negotiation-http-dispatcher-0.4.1.jar:$APP_HOME/lib/dsp-http-core-0.4.1.jar:$APP_HOME/lib/http-spi-0.4.1.jar:$APP_HOME/lib/control-plane-api-client-spi-0.4.1.jar:$APP_HOME/lib/dsp-api-configuration-0.4.1.jar:$APP_HOME/lib/dsp-catalog-transform-0.4.1.jar:$APP_HOME/lib/dsp-negotiation-transform-0.4.1.jar:$APP_HOME/lib/dsp-transfer-process-transform-0.4.1.jar:$APP_HOME/lib/dsp-http-spi-0.4.1.jar:$APP_HOME/lib/contract-spi-0.4.1.jar:$APP_HOME/lib/transfer-spi-0.4.1.jar:$APP_HOME/lib/auth-spi-0.4.1.jar:$APP_HOME/lib/http-0.4.1.jar:$APP_HOME/lib/jersey-core-0.4.1.jar:$APP_HOME/lib/jetty-core-0.4.1.jar:$APP_HOME/lib/jersey-providers-0.4.1.jar:$APP_HOME/lib/web-spi-0.4.1.jar:$APP_HOME/lib/transfer-data-plane-spi-0.4.1.jar:$APP_HOME/lib/data-plane-spi-0.4.1.jar:$APP_HOME/lib/dsp-spi-0.4.1.jar:$APP_HOME/lib/json-ld-0.4.1.jar:$APP_HOME/lib/validator-core-0.4.1.jar:$APP_HOME/lib/transform-core-0.4.1.jar:$APP_HOME/lib/json-ld-spi-0.4.1.jar:$APP_HOME/lib/transform-spi-0.4.1.jar:$APP_HOME/lib/state-machine-0.4.1.jar:$APP_HOME/lib/data-plane-http-spi-0.4.1.jar:$APP_HOME/lib/transaction-datasource-spi-0.4.1.jar:$APP_HOME/lib/policy-engine-0.4.1.jar:$APP_HOME/lib/policy-engine-spi-0.4.1.jar:$APP_HOME/lib/validator-spi-0.4.1.jar:$APP_HOME/lib/federated-catalog-spi-0.4.1.jar:$APP_HOME/lib/catalog-spi-0.4.1.jar:$APP_HOME/lib/policy-spi-0.4.1.jar:$APP_HOME/lib/asset-spi-0.4.1.jar:$APP_HOME/lib/jwt-core-0.4.1.jar:$APP_HOME/lib/jwt-spi-0.4.1.jar:$APP_HOME/lib/data-address-http-data-spi-0.4.1.jar:$APP_HOME/lib/core-spi-0.4.1.jar:$APP_HOME/lib/policy-evaluator-0.4.1.jar:$APP_HOME/lib/policy-model-0.4.1.jar:$APP_HOME/lib/transaction-spi-0.4.1.jar:$APP_HOME/lib/runtime-metamodel-0.4.1.jar:$APP_HOME/lib/okhttp-dnsoverhttps-4.12.0.jar:$APP_HOME/lib/failsafe-okhttp-3.3.2.jar:$APP_HOME/lib/okhttp-4.12.0.jar:$APP_HOME/lib/okio-jvm-3.6.0.jar:$APP_HOME/lib/kotlin-stdlib-jdk8-1.9.10.jar:$APP_HOME/lib/kotlin-stdlib-jdk7-1.9.10.jar:$APP_HOME/lib/kotlin-stdlib-1.9.10.jar:$APP_HOME/lib/annotations-24.0.1.jar:$APP_HOME/lib/swagger-jaxrs2-jakarta-2.2.15.jar:$APP_HOME/lib/swagger-integration-jakarta-2.2.15.jar:$APP_HOME/lib/swagger-core-jakarta-2.2.15.jar:$APP_HOME/lib/swagger-models-jakarta-2.2.15.jar:$APP_HOME/lib/jersey-media-json-jackson-3.1.3.jar:$APP_HOME/lib/jackson-jakarta-rs-json-provider-2.15.3.jar:$APP_HOME/lib/jackson-module-jakarta-xmlbind-annotations-2.15.3.jar:$APP_HOME/lib/jackson-annotations-2.15.3.jar:$APP_HOME/lib/jackson-datatype-jakarta-jsonp-2.15.3.jar:$APP_HOME/lib/jackson-jakarta-rs-base-2.15.3.jar:$APP_HOME/lib/jackson-dataformat-yaml-2.15.3.jar:$APP_HOME/lib/jackson-datatype-jsr310-2.15.3.jar:$APP_HOME/lib/jackson-databind-2.15.3.jar:$APP_HOME/lib/jackson-core-2.15.3.jar:$APP_HOME/lib/postgresql-42.4.0.jar:$APP_HOME/lib/flyway-core-9.0.1.jar:$APP_HOME/lib/failsafe-3.3.2.jar:$APP_HOME/lib/bcpkix-jdk18on-1.76.jar:$APP_HOME/lib/jersey-container-servlet-3.1.3.jar:$APP_HOME/lib/jersey-container-servlet-core-3.1.3.jar:$APP_HOME/lib/jersey-server-3.1.3.jar:$APP_HOME/lib/jersey-media-multipart-3.1.3.jar:$APP_HOME/lib/jersey-hk2-3.1.3.jar:$APP_HOME/lib/jersey-client-3.1.3.jar:$APP_HOME/lib/jersey-common-3.1.3.jar:$APP_HOME/lib/jersey-entity-filtering-3.1.3.jar:$APP_HOME/lib/jakarta.ws.rs-api-3.1.0.jar:$APP_HOME/lib/nimbus-jose-jwt-9.37.jar:$APP_HOME/lib/opentelemetry-instrumentation-annotations-1.31.0.jar:$APP_HOME/lib/opentelemetry-api-1.31.0.jar:$APP_HOME/lib/commons-pool2-2.12.0.jar:$APP_HOME/lib/checker-qual-3.5.0.jar:$APP_HOME/lib/jakarta.json-2.0.1.jar:$APP_HOME/lib/bcutil-jdk18on-1.76.jar:$APP_HOME/lib/bcprov-jdk18on-1.76.jar:$APP_HOME/lib/swagger-annotations-jakarta-2.2.19.jar:$APP_HOME/lib/classgraph-4.8.154.jar:$APP_HOME/lib/javassist-3.29.2-GA.jar:$APP_HOME/lib/snakeyaml-2.1.jar:$APP_HOME/lib/jcip-annotations-1.0-1.jar:$APP_HOME/lib/titanium-json-ld-1.3.2.jar:$APP_HOME/lib/opentelemetry-context-1.31.0.jar:$APP_HOME/lib/websocket-jakarta-server-11.0.18.jar:$APP_HOME/lib/jetty-annotations-11.0.18.jar:$APP_HOME/lib/websocket-servlet-11.0.18.jar:$APP_HOME/lib/websocket-core-server-11.0.18.jar:$APP_HOME/lib/jetty-plus-11.0.18.jar:$APP_HOME/lib/jetty-webapp-11.0.18.jar:$APP_HOME/lib/jetty-servlet-11.0.18.jar:$APP_HOME/lib/jetty-security-11.0.18.jar:$APP_HOME/lib/jetty-server-11.0.18.jar:$APP_HOME/lib/jetty-jakarta-servlet-api-5.0.2.jar:$APP_HOME/lib/jakarta.json-api-2.1.1.jar:$APP_HOME/lib/jakarta.annotation-api-2.1.1.jar:$APP_HOME/lib/jakarta.inject-api-2.0.1.jar:$APP_HOME/lib/jakarta.validation-api-3.0.2.jar:$APP_HOME/lib/osgi-resource-locator-1.0.3.jar:$APP_HOME/lib/jakarta.xml.bind-api-4.0.0.jar:$APP_HOME/lib/mimepull-1.9.15.jar:$APP_HOME/lib/hk2-locator-3.0.4.jar:$APP_HOME/lib/websocket-jakarta-client-11.0.18.jar:$APP_HOME/lib/websocket-jakarta-common-11.0.18.jar:$APP_HOME/lib/jetty-jakarta-websocket-api-2.0.0.jar:$APP_HOME/lib/websocket-core-client-11.0.18.jar:$APP_HOME/lib/jetty-client-11.0.18.jar:$APP_HOME/lib/websocket-core-common-11.0.18.jar:$APP_HOME/lib/jetty-http-11.0.18.jar:$APP_HOME/lib/jetty-alpn-client-11.0.18.jar:$APP_HOME/lib/jetty-io-11.0.18.jar:$APP_HOME/lib/jetty-jndi-11.0.18.jar:$APP_HOME/lib/jetty-xml-11.0.18.jar:$APP_HOME/lib/jetty-util-11.0.18.jar:$APP_HOME/lib/slf4j-api-2.0.5.jar:$APP_HOME/lib/commons-lang3-3.12.0.jar:$APP_HOME/lib/kotlin-stdlib-common-1.9.10.jar:$APP_HOME/lib/jakarta.activation-api-2.1.0.jar:$APP_HOME/lib/hk2-api-3.0.4.jar:$APP_HOME/lib/aopalliance-repackaged-3.0.4.jar:$APP_HOME/lib/hk2-utils-3.0.4.jar:$APP_HOME/lib/asm-commons-9.6.jar:$APP_HOME/lib/asm-tree-9.6.jar:$APP_HOME/lib/asm-9.6.jar:$APP_HOME/lib/jakarta.transaction-api-2.0.0.jar
+CLASSPATH=$APP_HOME/lib/launcher.jar:$APP_HOME/lib/postgres-flyway.jar:$APP_HOME/lib/data-dashboard-local.jar:$APP_HOME/lib/control-plane-core-0.3.1.jar:$APP_HOME/lib/control-plane-api-client-0.3.1.jar:$APP_HOME/lib/dsp-0.3.1.jar:$APP_HOME/lib/configuration-filesystem-0.3.1.jar:$APP_HOME/lib/vault-filesystem-0.3.1.jar:$APP_HOME/lib/management-api-0.3.1.jar:$APP_HOME/lib/transfer-data-plane-0.3.1.jar:$APP_HOME/lib/transfer-pull-http-receiver-0.3.1.jar:$APP_HOME/lib/data-plane-selector-api-0.3.1.jar:$APP_HOME/lib/data-plane-selector-core-0.3.1.jar:$APP_HOME/lib/data-plane-selector-client-0.3.1.jar:$APP_HOME/lib/data-plane-api-0.3.1.jar:$APP_HOME/lib/data-plane-core-0.3.1.jar:$APP_HOME/lib/data-plane-http-0.3.1.jar:$APP_HOME/lib/api-observability-0.3.1.jar:$APP_HOME/lib/iam-mock-0.3.1.jar:$APP_HOME/lib/auth-tokenbased-0.3.1.jar:$APP_HOME/lib/control-plane-sql-0.3.1.jar:$APP_HOME/lib/data-plane-instance-store-sql-0.3.1.jar:$APP_HOME/lib/sql-pool-apache-commons-0.3.1.jar:$APP_HOME/lib/contract-negotiation-store-sql-0.3.1.jar:$APP_HOME/lib/transfer-process-store-sql-0.3.1.jar:$APP_HOME/lib/sql-lease-0.3.1.jar:$APP_HOME/lib/asset-index-sql-0.3.1.jar:$APP_HOME/lib/contract-definition-store-sql-0.3.1.jar:$APP_HOME/lib/policy-definition-store-sql-0.3.1.jar:$APP_HOME/lib/sql-core-0.3.1.jar:$APP_HOME/lib/transaction-local-0.3.1.jar:$APP_HOME/lib/boot-0.3.1.jar:$APP_HOME/lib/federated-catalog-core-0.3.1.jar:$APP_HOME/lib/federated-catalog-api-0.3.1.jar:$APP_HOME/lib/contract-core-0.3.1.jar:$APP_HOME/lib/transfer-core-0.3.1.jar:$APP_HOME/lib/connector-core-0.3.1.jar:$APP_HOME/lib/control-plane-aggregate-services-0.3.1.jar:$APP_HOME/lib/asset-api-0.3.1.jar:$APP_HOME/lib/catalog-api-0.3.1.jar:$APP_HOME/lib/contract-agreement-api-0.3.1.jar:$APP_HOME/lib/contract-definition-api-0.3.1.jar:$APP_HOME/lib/contract-negotiation-api-0.3.1.jar:$APP_HOME/lib/policy-definition-api-0.3.1.jar:$APP_HOME/lib/transfer-process-api-0.3.1.jar:$APP_HOME/lib/dsp-catalog-0.3.1.jar:$APP_HOME/lib/dsp-catalog-api-0.3.1.jar:$APP_HOME/lib/dsp-negotiation-0.3.1.jar:$APP_HOME/lib/dsp-negotiation-api-0.3.1.jar:$APP_HOME/lib/dsp-transfer-process-0.3.1.jar:$APP_HOME/lib/dsp-transfer-process-api-0.3.1.jar:$APP_HOME/lib/dsp-transfer-process-http-dispatcher-0.3.1.jar:$APP_HOME/lib/control-plane-spi-0.3.1.jar:$APP_HOME/lib/dsp-catalog-http-dispatcher-0.3.1.jar:$APP_HOME/lib/dsp-negotiation-http-dispatcher-0.3.1.jar:$APP_HOME/lib/dsp-http-core-0.3.1.jar:$APP_HOME/lib/data-plane-client-0.3.1.jar:$APP_HOME/lib/http-spi-0.3.1.jar:$APP_HOME/lib/control-plane-api-client-spi-0.3.1.jar:$APP_HOME/lib/dsp-api-configuration-0.3.1.jar:$APP_HOME/lib/dsp-catalog-transform-0.3.1.jar:$APP_HOME/lib/dsp-negotiation-transform-0.3.1.jar:$APP_HOME/lib/dsp-transfer-process-transform-0.3.1.jar:$APP_HOME/lib/dsp-http-spi-0.3.1.jar:$APP_HOME/lib/catalog-core-0.3.1.jar:$APP_HOME/lib/dsp-spi-0.3.1.jar:$APP_HOME/lib/json-ld-0.3.1.jar:$APP_HOME/lib/management-api-configuration-0.3.1.jar:$APP_HOME/lib/control-api-configuration-0.3.1.jar:$APP_HOME/lib/api-core-0.3.1.jar:$APP_HOME/lib/transform-core-0.3.1.jar:$APP_HOME/lib/federated-catalog-spi-0.3.1.jar:$APP_HOME/lib/catalog-spi-0.3.1.jar:$APP_HOME/lib/contract-spi-0.3.1.jar:$APP_HOME/lib/transfer-spi-0.3.1.jar:$APP_HOME/lib/auth-spi-0.3.1.jar:$APP_HOME/lib/http-0.3.1.jar:$APP_HOME/lib/jersey-core-0.3.1.jar:$APP_HOME/lib/jetty-core-0.3.1.jar:$APP_HOME/lib/jersey-providers-0.3.1.jar:$APP_HOME/lib/web-spi-0.3.1.jar:$APP_HOME/lib/transfer-data-plane-spi-0.3.1.jar:$APP_HOME/lib/data-plane-util-0.3.1.jar:$APP_HOME/lib/data-plane-spi-0.3.1.jar:$APP_HOME/lib/data-plane-selector-spi-0.3.1.jar:$APP_HOME/lib/validator-core-0.3.1.jar:$APP_HOME/lib/aggregate-service-spi-0.3.1.jar:$APP_HOME/lib/json-ld-spi-0.3.1.jar:$APP_HOME/lib/transform-spi-0.3.1.jar:$APP_HOME/lib/state-machine-0.3.1.jar:$APP_HOME/lib/data-plane-http-spi-0.3.1.jar:$APP_HOME/lib/transaction-datasource-spi-0.3.1.jar:$APP_HOME/lib/policy-engine-0.3.1.jar:$APP_HOME/lib/policy-engine-spi-0.3.1.jar:$APP_HOME/lib/validator-spi-0.3.1.jar:$APP_HOME/lib/policy-spi-0.3.1.jar:$APP_HOME/lib/asset-spi-0.3.1.jar:$APP_HOME/lib/jwt-core-0.3.1.jar:$APP_HOME/lib/jwt-spi-0.3.1.jar:$APP_HOME/lib/core-spi-0.3.1.jar:$APP_HOME/lib/util-0.3.1.jar:$APP_HOME/lib/policy-evaluator-0.3.1.jar:$APP_HOME/lib/policy-model-0.3.1.jar:$APP_HOME/lib/transaction-spi-0.3.1.jar:$APP_HOME/lib/runtime-metamodel-0.3.1.jar:$APP_HOME/lib/okhttp-dnsoverhttps-4.11.0.jar:$APP_HOME/lib/failsafe-okhttp-3.3.2.jar:$APP_HOME/lib/okhttp-4.11.0.jar:$APP_HOME/lib/okio-jvm-3.2.0.jar:$APP_HOME/lib/kotlin-stdlib-jdk8-1.6.20.jar:$APP_HOME/lib/kotlin-stdlib-jdk7-1.6.20.jar:$APP_HOME/lib/kotlin-stdlib-1.6.20.jar:$APP_HOME/lib/annotations-24.0.1.jar:$APP_HOME/lib/swagger-jaxrs2-jakarta-2.2.15.jar:$APP_HOME/lib/swagger-integration-jakarta-2.2.15.jar:$APP_HOME/lib/swagger-core-jakarta-2.2.15.jar:$APP_HOME/lib/swagger-models-jakarta-2.2.15.jar:$APP_HOME/lib/jersey-media-json-jackson-3.1.3.jar:$APP_HOME/lib/jackson-jakarta-rs-json-provider-2.15.2.jar:$APP_HOME/lib/jackson-module-jakarta-xmlbind-annotations-2.15.2.jar:$APP_HOME/lib/jackson-annotations-2.15.2.jar:$APP_HOME/lib/jackson-datatype-jakarta-jsonp-2.15.2.jar:$APP_HOME/lib/jackson-jakarta-rs-base-2.15.2.jar:$APP_HOME/lib/jackson-dataformat-yaml-2.15.2.jar:$APP_HOME/lib/jackson-datatype-jsr310-2.15.2.jar:$APP_HOME/lib/jackson-databind-2.15.2.jar:$APP_HOME/lib/jackson-core-2.15.2.jar:$APP_HOME/lib/postgresql-42.4.0.jar:$APP_HOME/lib/flyway-core-9.0.1.jar:$APP_HOME/lib/failsafe-3.3.2.jar:$APP_HOME/lib/bcpkix-jdk18on-1.76.jar:$APP_HOME/lib/jersey-container-servlet-3.1.3.jar:$APP_HOME/lib/jersey-container-servlet-core-3.1.3.jar:$APP_HOME/lib/jersey-server-3.1.3.jar:$APP_HOME/lib/jersey-media-multipart-3.1.3.jar:$APP_HOME/lib/jersey-hk2-3.1.3.jar:$APP_HOME/lib/jersey-client-3.1.3.jar:$APP_HOME/lib/jersey-common-3.1.3.jar:$APP_HOME/lib/jersey-entity-filtering-3.1.3.jar:$APP_HOME/lib/jakarta.ws.rs-api-3.1.0.jar:$APP_HOME/lib/nimbus-jose-jwt-9.32.jar:$APP_HOME/lib/opentelemetry-instrumentation-annotations-1.29.0.jar:$APP_HOME/lib/opentelemetry-api-1.29.0.jar:$APP_HOME/lib/commons-pool2-2.11.1.jar:$APP_HOME/lib/checker-qual-3.5.0.jar:$APP_HOME/lib/jakarta.json-2.0.1.jar:$APP_HOME/lib/bcutil-jdk18on-1.76.jar:$APP_HOME/lib/bcprov-jdk18on-1.76.jar:$APP_HOME/lib/swagger-annotations-jakarta-2.2.15.jar:$APP_HOME/lib/classgraph-4.8.154.jar:$APP_HOME/lib/javassist-3.29.2-GA.jar:$APP_HOME/lib/snakeyaml-2.0.jar:$APP_HOME/lib/jcip-annotations-1.0-1.jar:$APP_HOME/lib/titanium-json-ld-1.3.2.jar:$APP_HOME/lib/opentelemetry-context-1.29.0.jar:$APP_HOME/lib/websocket-jakarta-server-11.0.16.jar:$APP_HOME/lib/jetty-annotations-11.0.16.jar:$APP_HOME/lib/websocket-servlet-11.0.16.jar:$APP_HOME/lib/websocket-core-server-11.0.16.jar:$APP_HOME/lib/jetty-plus-11.0.16.jar:$APP_HOME/lib/jetty-webapp-11.0.16.jar:$APP_HOME/lib/jetty-servlet-11.0.16.jar:$APP_HOME/lib/jetty-security-11.0.16.jar:$APP_HOME/lib/jetty-server-11.0.16.jar:$APP_HOME/lib/jetty-jakarta-servlet-api-5.0.2.jar:$APP_HOME/lib/jakarta.json-api-2.1.1.jar:$APP_HOME/lib/jakarta.annotation-api-2.1.1.jar:$APP_HOME/lib/jakarta.inject-api-2.0.1.jar:$APP_HOME/lib/jakarta.validation-api-3.0.2.jar:$APP_HOME/lib/osgi-resource-locator-1.0.3.jar:$APP_HOME/lib/jakarta.xml.bind-api-4.0.0.jar:$APP_HOME/lib/mimepull-1.9.15.jar:$APP_HOME/lib/hk2-locator-3.0.4.jar:$APP_HOME/lib/websocket-jakarta-client-11.0.16.jar:$APP_HOME/lib/websocket-jakarta-common-11.0.16.jar:$APP_HOME/lib/jetty-jakarta-websocket-api-2.0.0.jar:$APP_HOME/lib/websocket-core-client-11.0.16.jar:$APP_HOME/lib/jetty-client-11.0.16.jar:$APP_HOME/lib/websocket-core-common-11.0.16.jar:$APP_HOME/lib/jetty-http-11.0.16.jar:$APP_HOME/lib/jetty-alpn-client-11.0.16.jar:$APP_HOME/lib/jetty-io-11.0.16.jar:$APP_HOME/lib/jetty-jndi-11.0.16.jar:$APP_HOME/lib/jetty-xml-11.0.16.jar:$APP_HOME/lib/jetty-util-11.0.16.jar:$APP_HOME/lib/slf4j-api-2.0.5.jar:$APP_HOME/lib/kotlin-stdlib-common-1.6.20.jar:$APP_HOME/lib/commons-lang3-3.12.0.jar:$APP_HOME/lib/jakarta.activation-api-2.1.0.jar:$APP_HOME/lib/hk2-api-3.0.4.jar:$APP_HOME/lib/aopalliance-repackaged-3.0.4.jar:$APP_HOME/lib/hk2-utils-3.0.4.jar:$APP_HOME/lib/asm-commons-9.5.jar:$APP_HOME/lib/asm-tree-9.5.jar:$APP_HOME/lib/asm-9.5.jar:$APP_HOME/lib/jakarta.transaction-api-2.0.0.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -133,10 +131,13 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    if ! command -v java >/dev/null 2>&1
+    then
+        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
+    fi
 fi
 
 # Increase the maximum file descriptors if we can.
@@ -144,7 +145,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
         # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC3045
+        # shellcheck disable=SC2039,SC3045
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
@@ -152,7 +153,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
       '' | soft) :;; #(
       *)
         # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC3045
+        # shellcheck disable=SC2039,SC3045
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
@@ -197,11 +198,15 @@ if "$cygwin" || "$msys" ; then
     done
 fi
 
-# Collect all arguments for the java command;
-#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $LAUNCHER_OPTS can contain fragments of
-#     shell script including quotes and variable substitutions, so put them in
-#     double quotes to make sure that they get re-expanded; and
-#   * put everything else in single quotes, so that it's not re-expanded.
+
+# Add default JVM options here. You can also use JAVA_OPTS and LAUNCHER_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS=""
+
+# Collect all arguments for the java command:
+#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
+#     and any embedded shellness will be escaped.
+#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
+#     treated as '${Hostname}' itself on the command line.
 
 set -- \
         -classpath "$CLASSPATH" \
